# Generated by Django 4.1.2 on 2022-10-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
