# Generated by Django 4.1.2 on 2022-10-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormPostes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
